---
abstract: 'Checks for taintedness of variables'
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.143240'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-Taint
no_index:
  directory:
    - t
    - inc
requires:
  Scalar::Util: '0'
  Test::Builder: '0'
  Test::More: '0'
  Tie::Array: '0'
  Tie::Hash: '0'
  Tie::Scalar: '0'
  overload: '0'
resources:
  repository: https://github.com/petdance/test-taint
version: '1.08'
